### ISSUE TITLE
Incomprehensible manual

### ISSUE THREAD

**Issue by Qazxsw321w** [DaviSoEditando/DeepFaceLab-Runpod#1]
step1. "Create pod from "RunPod Desktop" template"
How to do it? There is no such option.
@DaviSoEditando
If you make a manual, make it relevant to reality, or DO NOT DO IT AT ALL!

**Comment by DaviSoEditando** [comment]
> step1. "Create pod from "RunPod Desktop" template" How to do it? There is no such option. @DaviSoEditando If you make a manual, make it relevant to reality, or DO NOT DO IT AT ALL!

They recently changed it and removed it, I'm glad I made a copy. And next time be kinder to those who do it for free.

https://runpod.io/gsc?template=4l0vm2cw43&ref=590sx73q

**Comment by Qazxsw321w** [comment]
> > Шаг 1. "Создать pod из шаблона "RunPod Desktop" Как это сделать? Такой возможности нет.  Если вы составляете методичку, сделайте ее релевантной реальности, или НЕ ДЕЛАЙТЕ ЭТОГО ВООБЩЕ!
> 
> Недавно его поменяли и убрали, я рад, что сделал копию. И в следующий раз будьте добрее к тем, кто делает это бесплатно.
> 
> https://runpod.io/gsc?template=4l0vm2cw43&ref=590sx73q

Thank you
